print(bool(0))
print(bool(1))
print('Stringlar uchun')
print(bool(""))
print(bool("asdf"))
print("Boolean uchun")
print(bool(True))
print(bool(False))
print("Container data typelar uchun")
print(bool([]))
print(bool([1, 2]))
print(bool(tuple())) 
print(bool((1, 2))) 
print(bool({}))
print(bool({"key": "value"})) 
print(bool(set()))
print(bool({1, 2, 4})) 